version: '3.8'

services:
  db:
    container_name: mysql_host
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=book_manager
      - TZ=Asia/Tokyo
